### ISSUE TITLE
Ensure user is logged into `npm`.

### ISSUE THREAD

**Issue by cpojer** [kittens/lerna#107] opened 2016-04-18 03:17 UTC
When the user isn't logged in to npm, lerna will create a commit and a tag but it will fail on publish. It would be good if lerna could revert the commit or check for whether the user is logged in upfront?

**Comment by thejameskyle** [comment] 2016-04-18 03:22
Duplicate of #55

**Closed by thejameskyle** 2016-04-18 03:22 UTC

**Comment by cpojer** [comment] 2016-04-18 03:24
Woops, sorry! Thanks for already tracking this.
